name: Build and Push Docker Image (SHA Tag)

on:
  push:
    branches:
      - main  # Triggers on push to main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image with SHA tag
        run: |
          docker build -t srusree/api-ipgeoloc:latest -t srusree/api-ipgeoloc:${{ github.sha }} .

      - name: Push Docker images
        run: |
          docker push srusree/api-ipgeoloc:latest
          docker push srusree/api-ipgeoloc:${{ github.sha }}

